version: "3.3"
volumes:
  db:
    driver:
      local
services:
  #PHP Service
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - tax-solution

  #MySQL Service
  db:
    image: mysql:8.0.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: income_tax
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    networks:
      - tax-solution

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 5000:80
    volumes:
      - ./:/var/www
      - ./touch.conf:/etc/nginx/conf.d/default.conf
    networks:
      - tax-solution

#Docker Networks
networks:
  tax-solution:
    driver: bridge
